services:
  nginx-proxy:
    build: ./nginx
    restart: always
    environment:
      - FLASK_SERVER_ADDR=flask-app:8000
    depends_on:
      - flask-app
    networks:
      - dokploy-network

  flask-app:
    build: ./flask
    restart: always
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
