services:
  nginx-proxy:
    build: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment:
      - FLASK_SERVER_ADDR=flask-app:8000
    depends_on:
      - flask-app
    # Removed healthcheck temporarily to ensure the app starts
    command: /app/start.sh
    networks:
      - dokploy-network

  flask-app:
    build: flask
    restart: always
    # Added network so nginx can see it
    networks:
      - dokploy-network
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:8000 app:app

networks:
  dokploy-network:
    external: true
